name: 'Set Environment Variables'
description: 'Load environment variables from a .env file'
inputs:
  varFilePath:
    description: 'Path to the .env file'
    required: true
runs:
  using: "composite"
  steps:
    - run: |
        while IFS='=' read -r key value; do
          if [[ ! "$key" =~ ^# && -n "$key" ]]; then
            echo "$key=$value" >> $GITHUB_ENV
          fi
        done < "${{ inputs.varFilePath }}"
      shell: bash
